export default ({palette}) => ({
  menuToggle: {
    display: 'block',
    position: 'relative',
    top: '50px',
    left: '50px',
    zIndex: '1',
    '-webkit-user-select': 'none',
    'user-select': 'none',
    textDecoration: 'none',
    color: '#232323',
    transition: 'color 0.3s ease',
    '&:hover': {
      color: 'tomato',
    },
    '& span:first-child': {
      transformOrigin: '0% 0%',
    },
    '& span:nth-last-child(2)': {
      transformOrigin: '0% 100%',
    },
  },
  input: {
    display: 'block',
    width: '2rem',
    height: '2rem',
    position: 'absolute',
    top: '-10px',
    left: '-10px',
    cursor: 'pointer',
    opacity: '0' /* hide this */,
    zIndex: '2' /* and place it over the hamburger */,
    '-webkit-touch-callout': 'none',
    '&:checked': {
      transform: 'none',
    },
    '&:checked span': {
      opacity: 1,
      transform: 'rotate(45deg) translate(-2px, -1px)',
      background: '#232323',
    },
    '&:checked span:nth-last-child(3)': {
      opacity: '0',
      transform: 'rotate(0deg) scale(0.2, 0.2)',
    },
    '&:checked span:nth-last-child(2)': {
      transform: 'rotate(-45deg) translate(0, -1px)',
    },
  },
  burger: {
    display: 'block',
    width: '33px',
    height: '4px',
    marginBottom: '5px',
    position: 'relative',
    background: ' #cdcdcd',
    borderRadius: '3px',
    zIndex: '1',
    transformOrigin: '4px 0px',
    transition: 'transform 0.5s cubic-bezier(0.77,0.2,0.05,1.0),background 0.5s cubic-bezier(0.77,0.2,0.05,1.0) , opacity 0.55s ease',
  },
  menu: {
    position: 'absolute',
    width: ' 300px',
    margin: '-100px 0 0 -50px',
    padding: '50px',
    paddingTop: '125px',
    background: '#ededed',
    'list-style-type': 'none',
    '-webkit-font-smoothing': 'antialiased',
    transformOrigin: '0% 0%',
    transform: 'translate(-100%, 0)',
    transition: 'transform 0.5s cubic-bezier(0.77,0.2,0.05,1.0)',
    '& li': {
      padding: '10px 0',
      fontSize: '22px',
    },
  },
  activeLink: {
    color: palette.red,
  },
})
